[package]
org = "nalaka"
name = "server"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

# Add these dependency sections
[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.1"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.6.1"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.3.2"

[[dependency]]
org = "ballerina"
name = "cloud"
version = "3.2.0"

[[dependency]]
org = "ballerinai"
name = "observe"
version = "0.0.0"

